input {
  file {
    path => "C:/Users/Hp/Desktop/llm/big data/project_inter/data/predictions.jsonl"
    start_position => "beginning"
    sincedb_path => "NUL"
    codec => "json"
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "infra_predictions"
  }
  stdout { codec => rubydebug }
}
