input {
  kafka {
    bootstrap_servers => "localhost:9092"
    topics => ["infra.predictions"]
    group_id => "logstash-predictions"
    codec => json
    auto_offset_reset => "latest"
  }
}

filter {
  date {
    match => ["@timestamp", "ISO8601"]
    target => "@timestamp"
  }

  mutate {
    add_field => {
      "[data_stream][type]" => "logs"
      "[data_stream][dataset]" => "infra_predictions"
      "[data_stream][namespace]" => "default"
    }
    convert => {
      "p_fail_5m" => "float"
      "threshold" => "float"
      "missing_ratio" => "float"
      "cpu_pct_mean" => "float"
      "mem_pct_mean" => "float"
      "latency_p95_ms_mean" => "float"
      "error_count_sum" => "float"
      "queue_depth_mean" => "float"
      "net_retransmit_pct_mean" => "float"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    data_stream => true
    data_stream_type => "logs"
    data_stream_dataset => "infra_predictions"
    data_stream_namespace => "default"
    ecs_compatibility => "v8"
  }
  stdout {
    codec => rubydebug
  }
}
